title: 心渡的博客
email: 594892170@qq.com
description: > # this means to ignore newlines until "baseurl:"
  该页面是Xindu(心渡)的个人博客。博主为西安在校大一学生，目前还在学习当中。这个博客会记录一些自己的学习日志以及生活经历。
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xindu233.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Xindu # add your name
author-pic: adam-face.jpg
about-author: 博主Xindu(心渡)为西安在校大一学生，性别男，目前还在学习当中。对很多事情都有一点感兴趣，然而半途而废比较多(笑)。日常沉迷ACG，希望能快点等到EVA新剧场版(还有月姬remake)。现在的水平还很低，但是会不断提高自己。
# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: xindu233 # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
